---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jaje2231/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -r css $DEPLOYPATH
    - /bin/cp -r js $DEPLOYPATH
    - /bin/cp -r medias $DEPLOYPATH